apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: fastapi-vrcats
spec:
  containers:
  - image: vrcats/fastapiimage
    imagePullPolicy: IfNotPresent
    name: fastapi
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 100m